RUN_NAME: 'con_stl10_40_powoabsv4_1'
OUTPUT_DIR: 'model_ckpt'
CONT_TRAIN: False
RESUME: 'logs/con_stl10_40_powoabsv4_1/model_ckpt/last_checkpoint.pth'
SEED: 1
LOG_DIR: 'logs'
USE_CUDA: True
USE_TB: True
TB_DIR: 'tensorboard_runs/stl_10_40_run_0'
VALIDATE_ONLY: False
X_SHARP: True
RHO: 0.05

DATASET:
  PREPARE: False
  DIR: '../data'
  NAME: 'stl10'
  NUM_LABELED: 40
  NUM_CLASSES: 10
  NUM_WORKERS: 8
  CONVERT_ONE_HOT: False
  IMG_SIZE: 96
  URATIO: 7
  TRAIN_BATCH_SIZE: 64
  TEST_BATCH_SIZE: 512
  CROP_RATIO: 0.875
  PIXEL_MEAN: [0.44087965, 0.42790789, 0.38678672]
  PIXEL_STD: [0.23089217, 0.22623343, 0.22368798]
  RANDAUG_N: 3

MODEL:
  NAME: 'wrn_37_2'
  PRETRAINED: False
  PRETRAINED_PATH: ''

OPTIMIZER:

  NAME: 'SGD'
  LR: 0.03
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
  SKIP_BN: True

TRAINER:

  SAT_EMA: 0.999
  AMP_ENABLED: True
  NUM_WARMUP_ITERS: 0
  NUM_TRAIN_ITERS: 1048576 # 2^20
  NUM_EVAL_ITERS: 512
  NUM_LOG_ITERS: 512
  EMA_VAL: 0.999
  ULB_LOSS_RATIO: 1.0
  ENT_LOSS_RATIO: 0.05
  POLOSS: True
  GPU: 3